spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      # 路由规则
      routes:
        # Auth服务路由
        - id: tumo-cloud-auth
          uri: lb://tumo-cloud-auth
#          uri: http://localhost:3000/
          predicates:
            - Path=/tumo-cloud/auth/**
          filters:
            - StripPrefix=2

