server:
  port: 5002
  servlet:
    session:
      cookie:
        name: sentinel_dashboard_cookie

auth:
  username: Tumo-Cloud
  password: Tumo-Cloud
  filter:
    exclude-urls: /,/auth/login,/auth/logout,/registry/machine,/version
    exclude-url-suffixes: htm,html,js,css,map,ico,ttf,woff,png

sentinel:
  dashboard:
    version: 1.8.1
